### ISSUE TITLE
No Big Image in Album

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#13]
Here is my personal album. Notice no large image? It only shows the name of the image in blue? If you click the blue image name it opens up the image.

![screenshot_34](https://cloud.githubusercontent.com/assets/2566493/18486333/610a11a2-79b6-11e6-8d6c-3b8810262315.jpg)

**Comment by MWE001** [comment]
I called this a bug but it may not be. I might have missed a setting somewhere but I don't think so. I went through admin panel 4 times for the album.

**Comment by vendethiel** [comment]
Keep me posted.

**Comment by vendethiel** [comment]
Found it. Fixed it.

**Comment by MWE001** [comment]
I got the very same problem on Little elm as well. BUT it is kind of hard for me to use that site right now as a control due to the image issues it is having at the moment.

**Comment by MWE001** [comment]
Ah ok cool. You beat me to it. lol Im hung up on the bbcode boxes at the moment

I did fix several things today. I got some for icy I want to work on today as well. I'll be eating dinner and switching modes here in an hour or two.
