### ISSUE TITLE
Error When Trying To Add Comment In Downloads

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#16]
Here is a good one.

This is when I went to comment to test the bbcode box out on the downloads. I didn't even get as far as the bbcode box.

![screenshot_38](https://cloud.githubusercontent.com/assets/2566493/18491667/135024a8-79cd-11e6-9830-2c75be71fda7.jpg)

**Comment by vendethiel** [comment]
fixed. also fixed another CTracker bug related to this page.

**Comment by MWE001** [comment]
Ah good old cracker tracker.
