### ISSUE TITLE
.css Issue in Chrome

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#18]
![chrome_integra](https://cloud.githubusercontent.com/assets/2566493/18492659/0af6a50c-79d2-11e6-8182-5ac3e9acbf3e.jpg)

**Comment by MWE001** [comment]
Bottom nav bar does not stretch like the top one does.

**Comment by IntegraMOD** [comment]
youll have to do this to all templates.
OPEN 
overall_footer.tpl
FIND
```
		  <table border="0" cellpadding="0" cellspacing="0">
	  	    <tr>
			  <td class="btm">
```
INLINE FIND
`cellspacing="0"`
AFTER, ADD
` width="100%"`
