### ISSUE TITLE
Youtube BBCode Posting Forums

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#19]
`[youtube]URL INSERTED HERE[/youtube]`

This BBCode no longer works.

**Comment by vendethiel** [comment]
Someone fixed it for me. There are two fixes. You can get it from my EzArena repo on my profile (click commits, pick the ones from Phosphorus-M)

**Comment by MWE001** [comment]
I apparently am not doing something right. I went to your Git, clicked commits that had a few hundred of them I guess and all of them had your avatar on them. I never saw anything from anyone. Did I do it wrong? I'm still a Git newbie even though I been a member for years. lol Ive actually only been actively using it a week or so now.

**Comment by MWE001** [comment]
Found it! Thanks man. I'm going to give it a go.

**Comment by vendethiel** [comment]
Sorey. Seems you found it, but for completeness' sake: my profile > repositories > find ezarena > click > click commits :)

**Comment by MWE001** [comment]
Yep, fix works a treat. Thanks for the pointing it out to me.
