### ISSUE TITLE
Advanced BBCode Box 5.0.0 KB

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#20]
BBCode box does not work in the KB. Can it be upgraded? I'll have to see. The only thing that works in the entire box is the drop downs.

**Comment by MWE001** [comment]
I confirmed that the BBCode box buttons DO in fact work in Integramod 1.4.1 but not in Integramod 1.5.0

**Comment by MWE001** [comment]
Ok `<script language="javascript" type="text/javascript" src="mods/bbcode_box/bbcode_box.js"></script>`

That code allows the BBCode box to work properly. Is there any reason we can't use it?

**Comment by vendethiel** [comment]
None. Go ahead.

**Comment by MWE001** [comment]
Roger
