### ISSUE TITLE
Links Block Error

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#21]
![screenshot_40](https://cloud.githubusercontent.com/assets/2566493/18495698/a21e05de-79e5-11e6-8fc4-6d54848b9f13.jpg)

The links block is throwing errors.

**Comment by MWE001** [comment]
And the bottom half of the block

![screenshot_41](https://cloud.githubusercontent.com/assets/2566493/18495805/52da675a-79e6-11e6-91ab-ccb190a3009c.jpg)

**Comment by MWE001** [comment]
Update to this.

This is when you go to IMPortal Configuration and turn on Show image on top and or bottom if not both top and bottom of Links block. If you turn the images off, the block works great. No errors at all.

Here is a shot of it working with images. I am trying to figure out the difference and why one works for me and the other does not.

![screenshot_43](https://cloud.githubusercontent.com/assets/2566493/18569415/0e7a47aa-7b68-11e6-9b00-4e5eab431ce4.jpg)

**Comment by MWE001** [comment]
This is seriously irritating me. So far the only difference I find in code is a few edits to the links_block.tpl that is not going to throw any errors. The  only other thing I know of is, extreme styles is updated.

**Comment by MWE001** [comment]
This issue is really eating at my @ss. I can not for the life of me fix it. The only way to stop it is to go in the IMPortal configuration and shut off the upper and lower images to the sites button.

**Comment by vendethiel** [comment]
I'll get to this right after the big PR :)
