### ISSUE TITLE
Public Info (Base info)

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#36]
Go to memberlist and look at someones profile under the base tab. Yeah not going to happen.

This is the version that I have though so not sure about the one Ven is working on.

**Comment by vendethiel** [comment]
I shall try. You can test my version BTW it's ready

**Comment by MWE001** [comment]
Yep, still on the same plan that we talked about this morn  I hadn't got to clean my WAMP out yet today. I plan on installing tonight and giving it a go.

**Comment by IntegraMOD** [comment]
is this solved? I have no trouble viewing profiles in the "Base info" tab either as admin or a new user

**Comment by vendethiel** [comment]
Yup, I fixed it in my last PR.

Thanks for the invite!

**Comment by MWE001** [comment]
I apologize for being so far behind guys. I'm glad this is fixed. I have not had a chance to look at anything. I had a catostraphic hard drive failure last night and net issues before.

I know before I had major issues installing on WAMP server and it was essentially a no go. I think Ven helped us fix. I am going to try tonight for 100% sure to get caught up.

**Comment by vendethiel** [comment]
No problem :-). It's been waiting since 201?, it can wait a few more days/weeks :).
