### ISSUE TITLE
Fisuborange and Fisublue swapped?

### ISSUE THREAD

**Issue by vendethiel** [IntegraMOD/IntegraMOD150#46]
Hey,
I just pulled from master and I'm a bit flabbergasted... Locally my fisubblue appears as fisuborange, and the opposite is also true. Is that just happening on my end or is that everybody's case?

**Comment by IntegraMOD** [comment]
only fisubice is current. All fisub templates use main.css for most css. The template named css files, ie.. fisubice.css only contain colors. should take a few more days to debug fisubice then Ill update the other files, like fisuborange etc..

**Comment by IntegraMOD** [comment]
the swap may also be caused by include/def_themes and the install schema not being synced. Ill check it tonight

**Comment by vendethiel** [comment]
Okay, thanks.

Out of curiosity – I'll derail this thread only to ask this single question – do you know a bit about PCP? I'm trying to figure some stuff out.

**Comment by IntegraMOD** [comment]
Its been awhile but I know a bit. What are you trying to do? Sometimes its easier to directly edit the root/profilcp/def/*.* files Just keep a backup of your work in case you get a white screen. Its pretty particular about formatting and any extra characters.

**Comment by IntegraMOD** [comment]
updated includes/def_themes.php to match the database on install.

**Comment by MWE001** [comment]
I am in a testing mood. Been fiddling with my server. Am I good to download this master and give it a shot tonight?

**Comment by IntegraMOD** [comment]
sure. The only fully working template is fisubice and fisublack. Hopefully I can update one a day till they are all up to date.

**Comment by MWE001** [comment]
Rgr that. I was just working on activity mod and got burnt for the night and decided to give a test install a go and see whats up. So yeah templates don't hurt my feelings any. I'm just going to mess with links , buttons, and what ever else I can check under the hood on. ;-)

**Comment by MWE001** [comment]
**DISCLAIMER**
I meant a test install of Integra, not activity mod.

**Comment by vendethiel** [comment]
fixed by 618f57d900ff7e8dd66f785345b4605e500c0b36
