### ISSUE TITLE
Album>Personal gallery: missing buttons

### ISSUE THREAD

**Issue by vendethiel** [IntegraMOD/IntegraMOD150#48]
I get missing icons when visiting my personal gallery.

![image](https://cloud.githubusercontent.com/assets/199499/20326337/97d92002-ab88-11e6-801d-973c3eea39c4.png)

**Comment by IntegraMOD** [comment]
my desktop git client always tells me it uploaded changes but sometimes it does not.

**Comment by IntegraMOD** [comment]
just updated root/album_mod/album_personal.php to add css to the links. There may be more missing buttons in the gallery but I havent found them yet
