### ISSUE TITLE
Serious error In the Album

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#5]
![screenshot_30](https://cloud.githubusercontent.com/assets/2566493/18465485/a93679c0-795c-11e6-98bc-dc5ccab1458c.jpg)
Not sure if it is due to my WAMP server or what. IM 150 does NOT like Localhost servers. That really needs fixed.

I'm gonna call this a bug until I know better.

**Comment by vendethiel** [comment]
I tried to visit the album page on my MAMP (mac) and it worked. Anything special to trigger the bug?

**Comment by MWE001** [comment]
Nope nothing at all. As soon as I logged in the ACP I went right to album to check it out and there it was. On multiple pages of the album config.

**Comment by vendethiel** [comment]
Okay, so ACP. will take a look later
