### ISSUE TITLE
chmod.php

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#6]
chmod.php is a great file and makes installing nice. However, it does NOT like localhost servers. This is an issue since many users like to build local and upload live.

**Comment by vendethiel** [comment]
Are you talking about the warnings?  Try adding this after `<?php`:

```
error_reporting(E_ALL);
```

**Comment by MWE001** [comment]
The whole entire page fills up with errors and rolls and rolls and rolls some more down the screen . have to scroll way back up to install.

**Comment by MWE001** [comment]
Love the new install chmod file man. Good job. It works flawless on my live server as well as localhost where as in my localhost it used to fail miserably.
