### ISSUE TITLE
RSS Feed Error

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD150#8]
This one should be an easy one to fix. Not in a hurry about it, but needs fixed. Bug!

![screenshot_33](https://cloud.githubusercontent.com/assets/2566493/18465718/c8a2bd90-795d-11e6-9f32-4d5e439fe8ce.jpg)

**Comment by vendethiel** [comment]
I have fixed it locally. Will send a PR when home.

**Comment by MWE001** [comment]
Ok thats cool. I'll be in bed. I'll check it out some time tomorrow for sure. I got some other work I need to do to but I want to try to knock a couple out here and a couple over there.
